name: Run Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint

      - name: Run Tests
        run: npm run test